# Generated by Django 3.0.6 on 2020-06-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('TP', 'Technical Problems'), ('RP', 'Refund Problems'), ('OP', 'Other Problems')], max_length=2)),
                ('message', models.TextField()),
            ],
        ),
    ]
