# Generated by Django 3.0.5 on 2020-04-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='social',
            name='platform',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
