# Generated by Django 3.0.5 on 2020-05-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_auto_20200428_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='organizer',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='organizer',
            name='secret_id',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='organizer',
            name='telegram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='organizer',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.DeleteModel(
            name='Social',
        ),
    ]
