# Generated by Django 3.0.6 on 2020-05-23 02:20

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0003_auto_20200501_1711'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='organizer',
            managers=[
                ('verified', django.db.models.manager.Manager()),
            ],
        ),
    ]
