# Generated by Django 3.0.6 on 2020-05-23 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0004_auto_20200523_0220'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='organizer',
            managers=[
            ],
        ),
    ]
