# Generated by Django 3.0.6 on 2020-06-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0005_auto_20200523_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
