# Generated by Django 3.0.7 on 2020-06-14 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0006_organizer_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_id', models.CharField(max_length=200)),
                ('ticket_code', models.CharField(max_length=200)),
                ('payment_type', models.CharField(max_length=100)),
                ('name_on_account', models.CharField(max_length=100)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizer.Organizer')),
            ],
        ),
    ]
