# Generated by Django 3.0.7 on 2020-06-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0007_requestpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestpayment',
            name='amount',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
