# Generated by Django 3.0.7 on 2020-06-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0008_requestpayment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestpayment',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='requestpayment',
            name='account_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='requestpayment',
            name='payment_option',
            field=models.CharField(choices=[('mobile_money', 'MM'), ('bank_account', 'BA')], default='MM', max_length=100),
        ),
    ]
