# Generated by Django 3.0.7 on 2020-06-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0009_auto_20200614_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestpayment',
            name='account_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='requestpayment',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='requestpayment',
            name='payment_option',
            field=models.CharField(choices=[('MM', 'mobile money'), ('BA', 'bank account')], max_length=100),
        ),
    ]
