# Generated by Django 3.0.7 on 2020-06-14 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0010_auto_20200614_2230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestpayment',
            options={'verbose_name': "Organizer's Payment Request", 'verbose_name_plural': 'Organizers payment requests'},
        ),
    ]
