# Generated by Django 3.0.7 on 2020-06-14 23:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0011_auto_20200614_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestpayment',
            name='request_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 14, 23, 20, 16, 362012, tzinfo=utc)),
        ),
    ]
