# Generated by Django 3.0.7 on 2020-06-14 23:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0012_requestpayment_request_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestpayment',
            name='request_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
