# Generated by Django 3.0.7 on 2020-06-14 23:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0013_auto_20200614_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestpayment',
            name='paid_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='requestpayment',
            name='request_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
