# Generated by Django 3.0.7 on 2020-06-14 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0014_auto_20200614_2323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestpayment',
            options={'ordering': ['-request_on'], 'verbose_name': "Organizer's Payment Request", 'verbose_name_plural': 'Organizers payment requests'},
        ),
    ]
