# Generated by Django 3.0.7 on 2020-06-14 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0015_auto_20200614_2323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestpayment',
            options={'ordering': ['-requested_on'], 'verbose_name': "Organizer's Payment Request", 'verbose_name_plural': 'Organizers payment requests'},
        ),
        migrations.RenameField(
            model_name='requestpayment',
            old_name='request_on',
            new_name='requested_on',
        ),
    ]
