# Generated by Django 3.0.7 on 2020-06-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0016_auto_20200614_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestpayment',
            name='status',
            field=models.CharField(choices=[('PEND', 'PENDING'), ('SUCCESS', 'SUCCESSFUL'), ('CANCEL', 'CANCELLED')], default='PEND', max_length=20),
        ),
    ]
