# Generated by Django 3.0.7 on 2020-06-14 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0017_requestpayment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestpayment',
            name='status',
            field=models.CharField(choices=[('PEND', 'PENDING'), ('SUCCESS', 'SUCCESSFUL'), ('CANCEL', 'CANCELLED')], max_length=20),
        ),
    ]
