# Generated by Django 3.0.5 on 2020-05-06 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizer', '0003_auto_20200501_1711'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('slug', models.SlugField(default='Slug-Field', help_text='This will be auto-generated [Unique Ticket ID]')),
                ('featured_image', models.ImageField(upload_to='ticket_images')),
                ('category', models.CharField(choices=[('CS', 'Concert Show'), ('SS', 'Summit Show'), ('MS', 'Movie Show'), ('FS', 'Sports Event'), ('PS', 'Party Event'), ('ES', 'Other Event')], max_length=10)),
                ('start_price', models.PositiveIntegerField()),
                ('end_price', models.PositiveIntegerField()),
                ('date_deadline', models.DateTimeField()),
                ('start_date_time', models.DateTimeField()),
                ('end_date_and_time', models.DateTimeField()),
                ('venue', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('is_suggested', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_most_featured', models.BooleanField(default=False)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizer.Organizer')),
            ],
        ),
        migrations.CreateModel(
            name='TicketVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.Ticket')),
            ],
        ),
        migrations.CreateModel(
            name='TicketItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('ordered', models.BooleanField(default=False)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.Ticket')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.TicketVariation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ticket_images')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.Ticket')),
            ],
        ),
        migrations.CreateModel(
            name='TicketBag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('ordered', models.BooleanField(default=False)),
                ('order_ref_code', models.CharField(max_length=100)),
                ('tickets', models.ManyToManyField(to='ticket.TicketItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
