# Generated by Django 3.0.5 on 2020-05-01 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizer', '0002_auto_20200428_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('slug', models.SlugField(help_text='This will be auto-generated [Unique Ticket ID]')),
                ('featured_image', models.ImageField(upload_to='ticket_images')),
                ('category', models.CharField(choices=[('CS', 'Concert Show'), ('SS', 'Summit Show'), ('MS', 'Movie Show'), ('FS', 'Sports Event'), ('PS', 'Party Event'), ('ES', 'Other Event')], max_length=10)),
                ('start_price', models.PositiveIntegerField()),
                ('end_price', models.PositiveIntegerField()),
                ('date_deadline', models.DateTimeField()),
                ('start_time', models.DateTimeField()),
                ('start_date', models.DateField()),
                ('end_time', models.DateTimeField()),
                ('end_date', models.DateField()),
                ('venue', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizer.Organizer')),
            ],
        ),
        migrations.CreateModel(
            name='TicketImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ticket_images')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.Ticket')),
            ],
        ),
    ]
