# Generated by Django 3.0.5 on 2020-05-01 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='end_time',
            new_name='end_date_and_time',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='start_time',
            new_name='start_date_time',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='start_date',
        ),
    ]
