# Generated by Django 3.0.5 on 2020-05-06 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketitem',
            name='slug',
            field=models.SlugField(default='Slug-Field'),
        ),
    ]
