# Generated by Django 3.0.5 on 2020-05-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_ticketitem_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
