# Generated by Django 3.0.5 on 2020-05-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20200501_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_most_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_suggested',
            field=models.BooleanField(default=False),
        ),
    ]
