# Generated by Django 3.0.5 on 2020-05-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_auto_20200504_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='slug',
            field=models.SlugField(default='Slug-Field', help_text='This will be auto-generated [Unique Ticket ID]'),
        ),
    ]
