# Generated by Django 3.0.5 on 2020-05-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_auto_20200509_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
