# Generated by Django 3.0.6 on 2020-05-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_auto_20200509_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketitem',
            name='qr_image',
            field=models.ImageField(null=True, upload_to='ticket_qrcode'),
        ),
    ]
