# Generated by Django 3.0.6 on 2020-05-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_ticketitem_qr_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketitem',
            name='qr_image_path',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
