# Generated by Django 3.0.6 on 2020-05-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_ticketitem_qr_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketitem',
            name='ticket_code',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
