# Generated by Django 3.0.6 on 2020-05-20 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_ticketitem_ticket_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketitem',
            name='qr_image',
        ),
        migrations.RemoveField(
            model_name='ticketitem',
            name='qr_image_path',
        ),
    ]
