# Generated by Django 3.0.6 on 2020-05-20 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_auto_20200520_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketItemQrImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_item_qr_image', models.ImageField(upload_to='ticket_qr_code')),
                ('ticket_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.TicketItem')),
            ],
        ),
    ]
