# Generated by Django 3.0.6 on 2020-05-23 02:22

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_ticketitemqrimage'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ticket',
            managers=[
                ('parties', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='ticketbag',
            managers=[
                ('ordered_ticket_bags', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='ticketbag',
            name='order_ref_code',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('CT', 'Concert Ticket'), ('ST', 'Summit Ticket'), ('MT', 'Movie Ticket'), ('ET', 'Esports Ticket'), ('PT', 'Party Ticket'), ('OT', 'Other Ticket')], max_length=10),
        ),
    ]
