# Generated by Django 3.0.6 on 2020-05-23 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_auto_20200523_0222'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ticket',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='ticketbag',
            managers=[
            ],
        ),
    ]
