# Generated by Django 3.0.6 on 2020-05-23 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0011_auto_20200523_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketbag',
            name='order_ref_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
