# Generated by Django 3.0.6 on 2020-05-24 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0012_ticketbag_order_ref_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketitem',
            name='ordered',
        ),
    ]
