# Generated by Django 3.0.6 on 2020-05-24 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0013_remove_ticketitem_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketbag',
            name='ordered',
        ),
    ]
