# Generated by Django 3.0.6 on 2020-05-24 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0014_remove_ticketbag_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketbag',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticketitem',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
