# Generated by Django 3.0.6 on 2020-05-31 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0015_auto_20200524_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='map_location',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='slug',
            field=models.SlugField(default='Slug-Field', help_text='This will be auto-generated [Unique Ticket ID]', max_length=1000),
        ),
    ]
