# Generated by Django 3.0.6 on 2020-06-02 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0018_auto_20200601_0650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedtickets',
            name='ticket',
        ),
        migrations.AddField(
            model_name='savedtickets',
            name='ticket',
            field=models.ManyToManyField(blank=True, to='ticket.Ticket'),
        ),
        migrations.AlterField(
            model_name='savedtickets',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
