# Generated by Django 3.0.6 on 2020-06-02 15:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0019_auto_20200602_1437'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SavedTickets',
            new_name='SavedTicket',
        ),
    ]
