# Generated by Django 3.0.6 on 2020-06-04 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0020_auto_20200602_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
