# Generated by Django 3.0.6 on 2020-06-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0021_ticket_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_most_suggested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('CT', 'Concert Ticket'), ('ST', 'Summit Ticket'), ('MT', 'Movie Ticket'), ('ET', 'Esports Ticket'), ('PT', 'Party Ticket'), ('OT', 'Other Ticket'), ('OE', 'Online Event')], max_length=10),
        ),
    ]
