# Generated by Django 3.0.6 on 2020-06-07 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0022_auto_20200607_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='is_most_suggested',
        ),
    ]
