# Generated by Django 3.0.6 on 2020-06-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0023_remove_ticket_is_most_suggested'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_most_suggested',
            field=models.BooleanField(default=False),
        ),
    ]
