# Generated by Django 3.0.7 on 2020-06-12 10:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0024_ticket_is_most_suggested'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketitem',
            name='ordered_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
